import React from 'react'
import { ThumbsUpIcon, ThumbsDownIcon, RefreshCwIcon } from 'lucide-react'
export function AISummary() {
  return (
    <div className="bg-white text-black rounded-lg shadow-sm border border-gray-200">
      <div className="border-b border-gray-200 px-6 py-4 flex items-center justify-between">
        <h2 className="text-xl font-semibold">AI Summary</h2>
        <button className="text-blue-600 flex items-center text-sm">
          <RefreshCwIcon size={16} className="mr-1" />
          <span>Regenerate</span>
        </button>
      </div>
      <div className="px-6 py-4">
        <div className="mb-6">
          <h3 className="text-lg font-medium mb-3">Meeting Overview</h3>
          <p className="text-gray-800 leading-relaxed">
            This product team standup meeting focused on three main topics:
            reviewing the current sprint status, discussing user feedback
            regarding notification controls, and planning for the new analytics
            dashboard feature. The team is 80% complete with the current sprint,
            with authentication flow improvements completed and dashboard
            redesign in QA with minor responsive design issues to fix.
          </p>
        </div>
        <div className="mb-6">
          <h3 className="text-lg font-medium mb-3">Key Points</h3>
          <ul className="list-disc pl-5 space-y-2 text-gray-800">
            <li>
              Current sprint is 80% complete with authentication flow
              improvements done and dashboard redesign in QA
            </li>
            <li>
              User feedback shows strong demand for better notification
              controls, especially from enterprise customers
            </li>
            <li>
              Enterprise customers specifically want role-based notification
              settings and time-based muting options
            </li>
            <li>
              The team plans to include improved notification controls in the
              next product update
            </li>
            <li>
              Sarah has completed initial backend work for the new analytics
              dashboard with good performance results
            </li>
          </ul>
        </div>
        <div className="mb-6">
          <h3 className="text-lg font-medium mb-3">Decisions Made</h3>
          <ul className="list-disc pl-5 space-y-2 text-gray-800">
            <li>
              Prioritize improved notification controls for the next sprint
            </li>
            <li>
              Taylor will start designing advanced notification controls this
              week
            </li>
            <li>
              Aim to include notification improvements in the next product
              update rather than waiting for the July release
            </li>
            <li>
              Focus on most requested notification features first, with plans to
              expand later
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-medium mb-3">Follow-up Questions</h3>
          <ul className="list-disc pl-5 space-y-2 text-gray-800">
            <li>
              What specific notification controls should be prioritized for the
              first iteration?
            </li>
            <li>
              Who will be responsible for QA testing the responsive design fixes
              for the dashboard?
            </li>
            <li>
              Is there a specific target date for the next product update?
            </li>
            <li>
              How will the team measure the success of the new notification
              controls?
            </li>
          </ul>
        </div>
      </div>
      <div className="border-t border-gray-200 px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="text-sm text-gray-500">
            Generated by AI • June 15, 2023
          </div>
          <div className="flex items-center space-x-4">
            <button className="text-gray-500 hover:text-gray-700 flex items-center text-sm">
              <ThumbsUpIcon size={16} className="mr-1" />
              <span>Helpful</span>
            </button>
            <button className="text-gray-500 hover:text-gray-700 flex items-center text-sm">
              <ThumbsDownIcon size={16} className="mr-1" />
              <span>Not helpful</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
